name: CI_Projucer_Test

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: Build plugin with Projucer
    runs-on: [self-hosted, macos]
    steps:

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: latest

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: "(JUCE) Clone Repository"
      uses: actions/checkout@v2
      with:
          repository: juce-framework/JUCE
          path: ${{runner.workspace}}/CI_Projucer_Test/JUCE

    - name: Build Projucer (MacOS)
      shell: bash
      run: xcodebuild -project Projucer.xcodeproj -jobs 4 | xcpretty
      working-directory: JUCE/extras/Projucer/Builds/MacOSX

    - name: Resave jucer
      shell: bash
      run: /Applications/Projucer.app/Contents/MacOS/Projucer --resave CI_Projucer_Test.jucer
      env:
        PROJUCER: ${{ matrix.jucer }}

    - name: Build Plugin (MacOS VST3)
      shell: bash
      run: xcodebuild -scheme "AudioPluginDemo - VST3" | xcpretty
      working-directory: Builds/MacOSX


    - name: Build Plugin (MacOS AU)
      shell: bash
      run: xcodebuild -scheme "AudioPluginDemo - AU" | xcpretty
      working-directory: Builds/MacOSX


    - name: Build Plugin (MacOS Standalone)
      shell: bash
      run: xcodebuild -scheme "AudioPluginDemo - Standalone Plugin" | xcpretty
      working-directory: Builds/MacOSX
