name: CI_Projucer_Test

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: Build plugin with Projucer
    runs-on: [self-hosted, macOS]
    steps:


    - name: xcode setup
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1.0'

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Projucer (MacOS)
      shell: bash
      run: xcodebuild -project Projucer.xcodeproj -jobs 4 | xcpretty
      working-directory: modules/JUCE/extras/Projucer/Builds/MacOSX

    - name: Resave jucer
      shell: bash
      run: $PROJUCER --resave SimplePlugin.jucer
      env:
        PROJUCER: ${{ matrix.jucer }}

    - name: Build Plugin (MacOS)
      shell: bash
      run: xcodebuild -project SimplePlugin.xcodeproj -jobs 4 | xcpretty
      working-directory: Builds/MacOSX
